### ISSUE TITLE
Failed to load the build-platformio package

### ISSUE THREAD

**Issue by philuser** [mdeboer/build-platformio#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: "openSUSE Tumbleweed"
**Thrown From**: [build-platformio](https://github.com/mdeboer/build-platformio) package 1.2.3

### Stack Trace

Failed to load the build-platformio package

```
At Cannot find module 'ini'

Error: Cannot find module 'ini'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/build-platformio/build-provider.js:20:20)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/build-platformio/main.js:3:57)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.enablePackage (/app.asar/src/package-manager.js:171:19)
    at /app.asar/node_modules/settings-view/lib/package-card.js:348:27)
    at HTMLButtonElement.dispatch (/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:10.2.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always)
     -1:10.2.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always)
     -1:09.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:09.1.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:09.1.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:09.1.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:09.1.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:56.1.0 platformio-ide:target:build (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:56.1.0 platformio-ide:target:build-/home/philuser/Developpements/uSystem/Arduino/Exemples/PCA9685 (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-clang 0.10.1 
build 0.67.0 
build-platformio 1.2.3 
busy 0.7.0 
busy-signal 1.3.0 
console-panel 0.2.1 
file-icons 2.1.2 
intentions 1.1.2 
language-ini 1.19.0 
linter 2.1.2 
linter-gcc 0.7.1 
linter-ui-default 1.2.2 
minimap 4.27.1 
particle-dev 0.1.21 
particle-dev-cloud-functions 0.1.0 
particle-dev-cloud-variables 0.1.0 
particle-dev-complete 1.0.1 
particle-dev-libraries 0.2.18 
particle-dev-profiles 0.1.15 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
tool-bar 1.1.0 
```

**Comment by mdeboer** [comment]
Try re-installing, apparently the required packages haven't been installed or installation was interrupted.
