### ISSUE TITLE
Failed to load the build-platformio package

### ISSUE THREAD

**Issue by DienV138** [mdeboer/build-platformio#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [build-platformio](https://github.com/mdeboer/build-platformio) package 1.2.4

### Stack Trace

Failed to load the build-platformio package

```
At EPERM: operation not permitted, open 'C:\Users\vdc13\.atom\packages\build-platformio\main.js'

Error: EPERM: operation not permitted, open 'C:\Users\vdc13\.atom\packages\build-platformio\main.js'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Proxy.readFileSync (fs.js:342:35)
    at Proxy.fs.readFileSync (electron/js2c/asar.js:542:40)
    at compileFileAtPath (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:150787)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153451)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3507053
    at Package.measure (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3505853)
    at Package.load (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3506626)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384186)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:382914)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:385486)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:915033
    at r (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:909639)
    at n (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1194945)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195151)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
     -2:58.9.0 application:reopen-project (div#add-projects-view.)
  2x -2:52.2.0 editor:move-to-previous-subword-boundary (input.hidden-input)
```

### Non-Core Packages

```
build-platformio 1.2.4 
```

**Comment by mdeboer** [comment]
Please check the permissions of the Atom package as indicated by the exception message. Unfortunately I no longer plan to maintain this repository but feel free fork.
